# Tensor初始化方法

申请变量 Tensor时，一般使用 `tf.get_variable()`, 用到的初始化方法一般如下:

1. `tf.constant_initializer()`:Initializer that generates tensors with constant values.
2. `tf.ones_initializer()`:Initializer that generates tensors initialized to $1$.
3. `tf.zeros_initializer()`:Initializer that generates tensors initialized to $0$.
4. `tf.random_normal_initializer()`:Initializer that generates tensors with a normal distributio.
5. `tf.truncated_normal_initializer()`:Initializer that generates a truncated normal distributio.
6. `tf.random_uniform_initializer()`:Initializer that generates tensors with a uniform distributio.
7. `tf.uniform_unit_scaling_initializer()`:Initializer that generates tensors without scaling varianc.

## 例子说明

In [1]:
import tensorflow as tf

### `tf.constant_initializer()`

原型:`tf.constant_initializer(value, dtype, verify_shape)`. Initializer that generates tensors with constant values.

In [5]:
tf.reset_default_graph()

value = [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0]
init = tf.constant_initializer(value=value)

x1 = tf.get_variable("v1", shape=[2, 4], initializer=init)
x2 = tf.get_variable("v2", shape=[3, 4], initializer=init)
#x3 = tf.get_variable("v3", shape=[2, 3], initializer=init)

with tf.Session() as sess:
    tf.global_variables_initializer().run()
    
    print("fliting: {}".format(x1.eval()))
    print("larger: {}".format(x2.eval()))
    #print("smaller: {}".format(x3.eval()))

fliting: [[0. 1. 2. 3.]
 [4. 5. 6. 7.]]
larger: [[0. 1. 2. 3.]
 [4. 5. 6. 7.]
 [7. 7. 7. 7.]]


### `tf.ones_initializer()`

In [6]:
tf.reset_default_graph()

init = tf.ones_initializer(dtype=tf.float32)

x1 = tf.get_variable("x1", shape=[2, 4], initializer=init)

with tf.Session() as sess:
    tf.global_variables_initializer().run()
    
    print("x1: {}".format(x1.eval()))

x1: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### `tf.zeros_initializer()`

In [7]:
tf.reset_default_graph()

init = tf.zeros_initializer(dtype=tf.float32)

x1 = tf.get_variable("x1", shape=[2, 4], initializer=init)

with tf.Session() as sess:
    tf.global_variables_initializer().run()
    
    print("x1: {}".format(x1.eval()))

x1: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### `tf.random_normal_initializer()`

原型:`tf.random_normal_initializer(mean=0.0,stddev=1.0,seed=None,dtype=tf.float32)`. Initializer that generates tensors with a normal distributio.

In [14]:
tf.reset_default_graph()

init = tf.random_normal_initializer()

x1 = tf.get_variable("x1", shape=[2, 4], initializer=init)

with tf.Session() as sess:
    tf.global_variables_initializer().run()
    
    print("x1: {}".format(x1.eval()))

x1: [[-0.7895569  -0.10652571 -0.8467249   1.1024054 ]
 [ 2.5773494  -0.6237494   1.155529   -0.15168744]]


### `tf.truncated_normal_initializer()`

原型:`tf.truncated_normal_initializer(mean=0.0,stddev=1.0,seed=None,dtype=tf.float32)`. Initializer that generates a truncated normal distributio.

In [11]:
tf.reset_default_graph()

init = tf.truncated_normal_initializer()

x1 = tf.get_variable("x1", shape=[2, 4], initializer=init)

with tf.Session() as sess:
    tf.global_variables_initializer().run()
    
    print("x1: {}".format(x1.eval()))

x1: [[ 0.2831741   1.1158873  -1.7728971   0.15575412]
 [ 0.22755289  0.30561605  1.1741476   0.87317044]]


### `tf.random_uniform_initializer()`

原型: `tf.tf.random_uniform_initializer(minval=0,maxval=None,seed=None,dtype=tf.float32)`.Initializer that generates tensors with a uniform distributio.

In [12]:
tf.reset_default_graph()

init = tf.random_normal_initializer()

x1 = tf.get_variable("x1", shape=[2, 4], initializer=init)

with tf.Session() as sess:
    tf.global_variables_initializer().run()
    
    print("x1: {}".format(x1.eval()))

x1: [[-0.57111895 -0.06305406  1.6960198  -0.22203359]
 [-0.41994503 -1.3260975   0.9160734   1.0524141 ]]


### `tf.uniform_unit_scaling_initializer()`

原型:`tf.uniform_unit_scaling_initializer(factor=1.0,seed=None,dtype=tf.float32)`. Initializer that generates tensors without scaling varianc.

In [13]:
tf.reset_default_graph()

init = tf.uniform_unit_scaling_initializer()

x1 = tf.get_variable("x1", shape=[2, 4], initializer=init)

with tf.Session() as sess:
    tf.global_variables_initializer().run()
    
    print("x1: {}".format(x1.eval()))

Instructions for updating:
Use tf.initializers.variance_scaling instead with distribution=uniform to get equivalent behavior.
x1: [[-0.15356553 -0.58139044 -0.1909126  -0.5064564 ]
 [ 0.21269357 -0.08922446  0.01677608  0.46847892]]
