# 常数Tensor

In [1]:
import tensorflow as tf

## Constant Value Tensors

方法列表为:

1. `tf.zeros()`
2. `tf.zeros_like()`
3. `tf.ones()`
4. `tf.ones_like()`
5. `tf.fill()`
6. `tf.constant()`

In [2]:
tf.reset_default_graph()

x1 = tf.zeros(shape=[2, 3], dtype=tf.float32, name=None)
x2 = tf.zeros_like(x1)
x3 = tf.ones(shape=[2, 3], dtype=tf.float32, name=None)
x4 = tf.ones_like(x2)
x5 = tf.fill(dims=[2, 3], value=9)
x6 = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3])

with tf.Session() as sess:
    print("tf.zeros:{}".format(x1.eval()))
    print("tf.zeros_like:{}".format(x2.eval()))
    print("tf.ones:{}".format(x3.eval()))
    print("tf.ones_like:{}".format(x4.eval()))
    print("tf.fill:{}".format(x5.eval()))
    print("tf.constant:{}".format(x6.eval()))

tf.zeros:[[0. 0. 0.]
 [0. 0. 0.]]
tf.zeros_like:[[0. 0. 0.]
 [0. 0. 0.]]
tf.ones:[[1. 1. 1.]
 [1. 1. 1.]]
tf.ones_like:[[1. 1. 1.]
 [1. 1. 1.]]
tf.fill:[[9 9 9]
 [9 9 9]]
tf.constant:[[1. 2. 3.]
 [4. 5. 6.]]


## Sequences

方法列表为:

1. `tf.linspace()`
2. `tf.range()`

In [3]:
tf.reset_default_graph()

x1 = tf.linspace(start=1.0, stop=10.0, num=10)
x2 = tf.range(start=1.0, limit=10.0, delta=1.0)

with tf.Session() as sess:
    print("tf.linspace:{}".format(x1.eval()))
    print("tf.range:{}".format(x2.eval()))

tf.linspace:[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
tf.range:[1. 2. 3. 4. 5. 6. 7. 8. 9.]


## Random Tensors

方法列表为:

1. `tf.random_normal`:Outputs random values from a normal distribution.
2. `tf.truncated_normal`:Outputs random values from a truncated normal distributio.
3. `tf.random_uniform`:Outputs random values from a uniform distributio.
4. `tf.random_shuffle`:Randomly shuffles a tensor along its first dimensio.
5. `tf.random_crop`:Randomly crops a tensor to a given size.
6. `tf.multinomial`:Draws samples from a multinomial distributio.
7. `tf.random_gamma`:Draws shape samples from each of the given Gamma distribution(s).
8. `tf.set_random_seed`:Sets the graph-level random seed

In [4]:
tf.reset_default_graph()

tf.set_random_seed(1234)
x1 = tf.random_normal(shape=[2, 3], mean=0.0, stddev=1.0)
x2 = tf.truncated_normal(shape=[2, 3], mean=0.0, stddev=1.0)
x3 = tf.random_uniform(shape=[2, 3], minval=0, maxval=10)
x4 = tf.random_shuffle(value=[1.0, 2.0, 3.0, 4.0])
x5 = tf.random_crop(value=[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], size=[3])
x6 = tf.multinomial(logits=tf.log([[10., 10.]]), num_samples=5)
x7 = tf.random_gamma(shape=[10], alpha=[0.5, 1.5])

with tf.Session() as sess:
    print("tf.random_normal:{}".format(x1.eval()))
    print("tf.truncated_normal:{}".format(x2.eval()))
    print("tf.random_uniform:{}".format(x3.eval()))
    print("tf.random_shuffle:{}".format(x4.eval()))
    print("tf.random_crop:{}".format(x5.eval()))
    print("tf.multinomial:{}".format(x6.eval()))
    print("tf.random_gamma:{}".format(x7.eval()))

tf.random_normal:[[-0.1386252  -0.24789245 -0.22179745]
 [ 0.9156514   1.1768112  -2.1070724 ]]
tf.truncated_normal:[[-1.3978306  -0.16562939 -0.7687699 ]
 [ 1.327754   -0.17594577  0.4366916 ]]
tf.random_uniform:[[0.6164038 6.0531435 9.805503 ]
 [1.5821779 4.566201  7.6065993]]
tf.random_shuffle:[3. 2. 4. 1.]
tf.random_crop:[2. 3. 4.]
tf.multinomial:[[1 1 0 1 1]]
tf.random_gamma:[[0.08046223 0.45518064]
 [0.06306191 0.92751986]
 [1.0062762  0.7649951 ]
 [0.04033575 1.0296742 ]
 [0.09271713 1.9232417 ]
 [0.05965098 1.8720796 ]
 [1.6233451  0.9085234 ]
 [0.05325522 0.77123183]
 [0.00520489 0.80084515]
 [0.34794864 1.9822903 ]]
