In [1]:
import tensorflow as tf
from numpy.random import RandomState

#### 1.定义神经网络相关参数

In [2]:
batch_size = 8
x = tf.placeholder(tf.float32, shape=(None, 2), name='x-input')
y_ = tf.placeholder(tf.float32, shape=(None, 1), name="y-input")
w1 = tf.Variable(tf.random_normal(shape=[2, 1], stddev=1, seed=1))
y = tf.matmul(x, w1)

#### 2.设置自定义的损失函数

In [3]:
# 定义损失函数使得预测少了的损失大，于是模型应该偏向多的方向预测
loss_less = 10
loss_more = 1
loss = tf.reduce_sum(tf.where(tf.greater(y, y_), (y - y_)*loss_more, (y_ - y)*loss_less))
train_step = tf.train.AdamOptimizer(0.001).minimize(loss)

#### 3.生成模拟数据

In [4]:
#### 3.生成模拟数据集
rdm = RandomState(1)
X = rdm.rand(128, 2)
Y = [[x1+x2+(rdm.rand()/10.0-0.05)] for (x1, x2) in X]

#### 4.训练数据

In [5]:
config = tf.ConfigProto(allow_soft_placement=True)
with tf.Session(config=config) as sess:
    # 变量初始化
    tf.global_variables_initializer().run()
    
    STEPS = 5000
    for i in range(STEPS):
        start = (i*batch_size)%128
        end = (i*batch_size)%128 + batch_size
        sess.run(train_step, feed_dict={x: X[start:end], y_:Y[start:end]})
        if i % 1000 == 0:
            print("After %d training step(s), w1 is:" % (i))
            print(sess.run(w1), "\n")
    print("Final w1 is: \n", sess.run(w1))

After 0 training step(s), w1 is:
[[-0.81031823]
 [ 1.4855988 ]] 

After 1000 training step(s), w1 is:
[[ 0.01247114]
 [ 2.13854504]] 

After 2000 training step(s), w1 is:
[[ 0.45567423]
 [ 2.17060685]] 

After 3000 training step(s), w1 is:
[[ 0.69968736]
 [ 1.84653103]] 

After 4000 training step(s), w1 is:
[[ 0.89886677]
 [ 1.29736042]] 

Final w1 is: 
 [[ 1.01934707]
 [ 1.04280913]]


#### 5.重新定义损失函数，使得预测多了的损失大，于是模型应该偏向少的方向预测

In [8]:
loss_less = 1
loss_more = 10
loss = tf.reduce_sum(tf.where(tf.greater(y, y_), (y - y_)*loss_more, (y_ - y)*loss_less))
train_step = tf.train.AdamOptimizer(0.001).minimize(loss)

config = tf.ConfigProto(allow_soft_placement=True)
with tf.Session(config=config) as sess:
    # 变量初始化
    tf.global_variables_initializer().run()
    
    STEPS = 5000
    for i in range(STEPS):
        start = (i * batch_size)%128
        end = (i * batch_size)%128 + batch_size
        sess.run(train_step, feed_dict={x:X[start:end], y_:Y[start:end]})
        if i % 1000 == 0:
            print("After %d training step(s), w1 is: " % (i))
            print(sess.run(w1), "\n")
    print("Final w1 is: \n", sess.run(w1))

After 0 training step(s), w1 is: 
[[-0.81231821]
 [ 1.48359871]] 

After 1000 training step(s), w1 is: 
[[ 0.18643522]
 [ 1.07393348]] 

After 2000 training step(s), w1 is: 
[[ 0.95444274]
 [ 0.98088628]] 

After 3000 training step(s), w1 is: 
[[ 0.95574027]
 [ 0.98066342]] 

After 4000 training step(s), w1 is: 
[[ 0.95466024]
 [ 0.98135239]] 

Final w1 is: 
 [[ 0.95561111]
 [ 0.98101908]]


#### 6.定义损失函数为MSE

In [9]:
loss = tf.losses.mean_squared_error(y, y_)
train_step = tf.train.AdamOptimizer(0.001).minimize(loss)

config = tf.ConfigProto(allow_soft_placement=True)
with tf.Session(config=config) as sess:
    # 变量初始化
    tf.global_variables_initializer().run()
    STEPS = 5000
    for i in range(STEPS):
        start = (i*batch_size)%128
        end = (i*batch_size)%128 + batch_size
        sess.run(train_step, feed_dict={x:X[start:end], y_:Y[start:end]})
        if i % 1000 == 0:
            print("After %d training step(s), w1 is: " % (i))
            print(sess.run(w1), "\n")
    print("Final w1 is: \n", sess.run(w1))

After 0 training step(s), w1 is: 
[[-0.81031823]
 [ 1.4855988 ]] 

After 1000 training step(s), w1 is: 
[[-0.13337611]
 [ 1.81309223]] 

After 2000 training step(s), w1 is: 
[[ 0.32190308]
 [ 1.52463484]] 

After 3000 training step(s), w1 is: 
[[ 0.6785022 ]
 [ 1.25297272]] 

After 4000 training step(s), w1 is: 
[[ 0.8947401]
 [ 1.0859822]] 

Final w1 is: 
 [[ 0.97437561]
 [ 1.0243336 ]]
